/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import clases.Conexion;
import clases.Estudiante;
import static interfaz.captura.apellido1;
import static interfaz.captura.apellido2;
import static interfaz.captura.cedula;
import static interfaz.captura.celular;
import static interfaz.captura.correo;
import static interfaz.captura.direccion;
import static interfaz.captura.nombre1;
import static interfaz.captura.nombre2;
import static interfaz.captura.txtid;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class Edit_estudiante extends javax.swing.JFrame {

    Conexion con = new Conexion();
    Connection conexion = (Connection) con.conectar();
    PreparedStatement ps;
    ResultSet res;
    captura cap = new captura();

    public void limpiar() {
        nombre1.setText("");
        nombre2.setText("");
        cedula.setText("");
        apellido1.setText("");
        apellido2.setText("");
        correo.setText("");
        celular.setText("");
        direccion.setText("");
        hombre.setSelected(false);
        mujer.setSelected(false);
    }

    public Edit_estudiante() {
        initComponents();
        eliminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        apellido2 = new javax.swing.JTextField();
        hombre = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        mujer = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JTextField();
        nombre2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        apellido1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        celular = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Sitka Heading", 0, 36)); // NOI18N
        jLabel3.setText("Modificacion Estudiante");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setForeground(new java.awt.Color(0, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 84, 101, -1));

        buttonGroup1.add(hombre);
        hombre.setText("Hombre");
        hombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hombreActionPerformed(evt);
            }
        });
        jPanel2.add(hombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel9.setText("Genero");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        buttonGroup1.add(mujer);
        mujer.setText("Mujer");
        mujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mujerActionPerformed(evt);
            }
        });
        jPanel2.add(mujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel7.setText("Nombre_1:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel8.setText("Nombre_2:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 83, -1, -1));

        nombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre1ActionPerformed(evt);
            }
        });
        jPanel2.add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 20, 100, -1));
        jPanel2.add(nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 81, 100, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel2.setText("Apellido_2:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 86, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel5.setText("Apellido_1:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 20, -1, -1));

        apellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellido1ActionPerformed(evt);
            }
        });
        jPanel2.add(apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 20, 100, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel4.setText("Celular:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 86, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel6.setText("Correo");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 22, -1, -1));

        celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularActionPerformed(evt);
            }
        });
        jPanel2.add(celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 84, 110, -1));
        jPanel2.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 110, -1));

        jLabel13.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel13.setText("Cedula:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 152, 65, -1));
        jPanel2.add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 150, 103, -1));

        jLabel14.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel14.setText("Direccion:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 152, -1, -1));
        jPanel2.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 100, -1));

        jButton3.setText("Mostrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 274, 100, 40));

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 274, 100, 40));

        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1345823.png"))); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel2.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 274, -1, 40));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/7492386.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 297, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 610, 340));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit_modify_icon_149489.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 80, 80));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Ingrese ID:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 80, -1));

        jButton5.setText("Buscar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre1ActionPerformed

    private void celularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celularActionPerformed

    private void apellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellido1ActionPerformed

    private void hombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hombreActionPerformed

    private void mujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mujerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mujerActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Consulta open = new Consulta();
        open.setVisible(true);
        open.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int ident = Integer.parseInt(id.getText());
        String nom1 = nombre1.getText();
        String nom2 = nombre2.getText();
        String apel1 = apellido1.getText();
        String apel2 = apellido2.getText();
        String cel = celular.getText();
        String ced = cedula.getText();
        String dire = direccion.getText();
        String corr = correo.getText();

        Estudiante e = new Estudiante(ident, ced, nom1, nom2, apel1, apel2, dire, corr, cel);

        try {
            ps = conexion.prepareStatement("UPDATE estudiante SET Cedula=?, Nombre1=?, Nombre2=?, Apellido1=?, Apellido2=?, Genero=?, Direccion=?, Correo=?, Celular=? WHERE ID_estudiante=?;");

            ps.setString(1, e.getCedula());
            ps.setString(2, e.getNombre1());
            ps.setString(3, e.getNombre2());
            ps.setString(4, e.getApellido1());
            ps.setString(5, e.getApellido2());
            ps.setString(7, e.getDireccion());
            ps.setString(8, e.getCorreo());
            ps.setString(9, e.getCelular());
            ps.setInt(10, e.getID());

            //genero
            if (hombre.isSelected()) {
                ps.setString(6, "Hombre");
            } else if (mujer.isSelected()) {
                ps.setString(6, "Mujer");
            }

            int res = ps.executeUpdate();

            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Estudiante Modificado");
                limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Error al Modificar");
                limpiar();
            }

        } catch (SQLException c) {
            JOptionPane.showMessageDialog(null, c.getMessage(), "ERROR", ERROR);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        int ident = Integer.parseInt(id.getText());

        try {
            ps = conexion.prepareStatement("DELETE FROM estudiante WHERE ID_estudiante=?;");
            ps.setInt(1, ident);

            int re = ps.executeUpdate();

            if (re > 0) {
                ps = conexion.prepareStatement("DELETE FROM programa_estudiante WHERE ID_estudiante=?;");
                ps.setInt(1, ident);

                int respro = ps.executeUpdate();

                if (respro > 0) {
                    JOptionPane.showMessageDialog(null, "Estudiante Eliminado");
                    cap.limpiar();
                } else {
                    JOptionPane.showMessageDialog(null, "Error ");
                    cap.limpiar();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Error ");
                cap.limpiar();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int ident = Integer.parseInt(id.getText());

        try {
            ps = conexion.prepareStatement("SELECT * FROM estudiante WHERE ID_estudiante=?;");
            ps.setInt(1, ident);

            res = ps.executeQuery();

            if (res.next()) {
                cedula.setText(res.getString("Cedula"));
                nombre1.setText(res.getString("Nombre1"));
                nombre2.setText(res.getString("Nombre2"));
                apellido1.setText(res.getString("Apellido1"));
                apellido2.setText(res.getString("Apellido2"));
                direccion.setText(res.getString("Direccion"));
                correo.setText(res.getString("Correo"));
                celular.setText(res.getString("celular"));

                //genero
                String genero = res.getString("Genero");

                if (genero.equals("Masculino")) {
                    hombre.setSelected(true);
                } else if (genero.equals("Femenino")) {
                    mujer.setSelected(true);
                }

            } else {
                JOptionPane.showMessageDialog(null, "No Exite el estudiante");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Menu open = new Menu();
        open.setVisible(true);
        open.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_estudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField apellido1;
    public static javax.swing.JTextField apellido2;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JTextField cedula;
    public static javax.swing.JTextField celular;
    public static javax.swing.JTextField correo;
    public static javax.swing.JTextField direccion;
    private javax.swing.JButton eliminar;
    private javax.swing.JRadioButton hombre;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton mujer;
    public static javax.swing.JTextField nombre1;
    public static javax.swing.JTextField nombre2;
    // End of variables declaration//GEN-END:variables
}
